### ISSUE TITLE
Excessive indentation space in lsp-isar-state

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-emacs#39]
There is a lot of space on every line after "this: ..." in lsp-isar-state when the cursor is on a qed or sorry command in the main file.

**Comment by gh-salt** [comment]
Another problematic indentation issue (related) is when the cursor is in the main file on a "show" that fails: There is a missing carriage return (between goal and Local) in the first line in the lsp-isar-output file:
`Failed to refine any pending goalLocal statement fails to refine any pending goal`

**Comment by m-fleury** [comment]
- the missing linebreak was an error (the regexp intended to add it was not working...)
- the indentation is given by Isabelle. I have reduced the identation, to make it less ugly, but I am not certain if this is not causing some other issue.

**Comment by m-fleury** [comment]
Closing, because too old.
