### ISSUE TITLE
Renaming Repo

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-emacs#44]
If @m-fleury doesn't mind it, I suggest changing the repository name. `isabelle-release` looks like the just mirror of the official repository. I missed this repository when I searched such projects by Google.

_Originally posted by @tani in https://github.com/m-fleury/isabelle-release/issues/43#issuecomment-823024763_

**Comment by m-fleury** [comment]
I don't have a good alternative name, but I am open to suggestions. 

The problem is also that I don't want to scare users (and potential reviewers): It should not look like Isabelle changed compared to the official release. There are very few new functions, but everything is compatible with the normal Isabelle (same core, same Isabelle/jEdit).

There is actually some home that I might get some of the extensions in Isabelle.

**Comment by tani** [comment]
I see. It is difficult to name the better one for this repository.

How about `isabelle-emacs`? I know Isabelle/Emacs is not only an addition like the emacs package but also is a small modification of Isabelle. We, however, can recognize something related to emacs and Isabelle from the repository name at least.

**Comment by m-fleury** [comment]
I will rename it next week-end for `isabelle-emacs` (1. May) unless someone complaints about it.

**Comment by m-fleury** [comment]
TODO repo:
  - [ ] rename repo on github
  - [ ] change git link in Readme
 
TODO users:
  - [ ] replace remote in local git repo.

**Comment by m-fleury** [comment]
```
git remote set-url origin git@github.com:m-fleury/isabelle-emacs.git
```

**Comment by tani** [comment]
Thanks!
