### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by waynee95** [m-fleury/isabelle-emacs#49]
Hello! 
I am currently trying to get this working. I am usually a vim person and never really used emacs, nor did I spent time configuring any emacs before. 

I am running into a few issues and the instructions are a bit unclear sometimes. I am trying to get this working for spacemacs.

1. The instructions say to create an `isabelle` folder but then they state `cd local`. I would assume this is a typo?
2. Later the instructions say to "replace the imports by". Which imports and where exactly?

Thanks!

**Comment by m-fleury** [comment]
ThreeFx has a version for vim: https://github.com/ThreeFx/isabelle.vim if you want to try it out.

1. Yes, `isabelle` should be inside the `local` folder.
2. in `packages.el`, top of the file (if I count correctly, line 16).

**Comment by waynee95** [comment]
Thanks for the fast reply. I got it working, although I had to change one line.

In the instructions it said 
```
:repo "m-fleury/emacs-isabelle"
```
but shouldn't it be `isabelle-emacs`?

**Comment by m-fleury** [comment]
Good point. Seems that I forgot to rename that after #44.

**Comment by waynee95** [comment]
Since everything is working on my end now, I will close this.
