### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Torrencem** [m-fleury/isabelle-emacs#56]
I followed the installation instructions, and some parts of the plugin worked, while others don't. When I open a .thy file, the symbols etc. are substituted (so when I type combinations like =>, they are replaced with the appropriate symbol), so I know _something_ worked. However, when I open an isabelle file, I don't get any interface like the screenshots in the readme. In addition, when I manually call `M-x spacemacs/open-isar-output-and-progress-right`, I get 2 blank panels on the right that don't show anything, and it doesn't seem like anything is actually running in the .thy buffer I have open. 

Opening messages with `SPC w p m` shows no sorts of initialization messages, but does curiously show
```
Warnings:
- package dash not initialized in layer isabelle, you may consider removing this
package from the package list or use the :toggle keyword instead of a `when'
form.  
```
Other than that I have nothing to go off of. Any suggestions for troubleshooting?

I'm on a practically fresh install of Spacemacs with no other layers going on

**Comment by Torrencem** [comment]
One more clue, when I open a .thy buffer, manually call `open-isar-output-and-progress-right`, then check messages, I get
```
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
```

(although this hardly seems relevant at all)

**Comment by m-fleury** [comment]
Can send me the content of your `dotspacemacs-configuration-layers`? (SPC-f-e-D, then the content in `'(  ...)` right after `dotspacemacs-configuration-layers`, probably several lines). 

dash should be already loaded, which is why it is not initialised again. But apparently that does not hold for you.

**Comment by Torrencem** [comment]
```
   dotspacemacs-configuration-layers
   '(
     isabelle
     yaml
     emacs-lisp
     helm
     multiple-cursors
     )
```

**Comment by Torrencem** [comment]
A goofy step in [the installation](https://github.com/m-fleury/isabelle-emacs/blob/Isabelle2021-more-vscode/src/Tools/emacs-lsp/spacemacs_layers/isabelle/README.org) that I might have misunderstood is when it asked to "Replace the imports by `code`", I took that to mean editing `packages.el` to include the given snippet instead of the `isabelle-packages` that was already there. Is this what is intended?

**Comment by Torrencem** [comment]
([my entire spacemacs dotfile](https://gist.github.com/Torrencem/6b8d9a997d29cc418872ebb3cf1e297b), really shouldn't be anything going on there)

**Comment by m-fleury** [comment]
Two problems: 
  - [ ] the documentation is not up-to-date, you should only change the isar related lines (so in particular not add dash)
  - [ ] there is an implicit dependency to transient.

**Comment by m-fleury** [comment]
Can you:
 1. add git to your layers
 2. Change the imports to
 ```
    (isar-mode :location (recipe
                             :fetcher github
                             :repo "m-fleury/isar-mode"))
    (isar-goal-mode :location (recipe
                             :fetcher github
                             :repo "m-fleury/simp-isar-mode"))
    (lsp-isar :location (recipe
                             :fetcher github
                             :repo "m-fleury/isabelle-emacs"
                 :files ("src/Tools/emacs-lsp/lsp-isar/*.el")))
    (lsp-isar-parse-args :location (recipe
                             :fetcher github
                             :repo "m-fleury/isabelle-emacs"
                 :files ("src/Tools/emacs-lsp/lsp-isar/*.el")))
    session-async
    transient
    yasnippet
``` 
and tell me if it works now?

(transient is part of magit, which is part of the git layer…)

**Comment by Torrencem** [comment]
I'm now getting errors installing `session-async` (this is after fixing other errors by updating spacemacs):
```
(Spacemacs) Error: 
An error occurred while installing session-async (error: (error Package ‘emacs-27.1’ is unavailable))
```
removing `session-async` from the list gives
```
Warnings:
    - package transient not initialized in layer isabelle, you may consider removing
      this package from the package list or use the :toggle keyword instead of a
      `when' form.      
```
then the same issue is happening (no response from the lsp)

**Comment by Torrencem** [comment]
I'm trying reinstalling all packages by removing `.spacemacs` and restarting...

**Comment by Torrencem** [comment]
That did not work. My dotspacemacs-configuration-layers:
```
   '(
     isabelle
     yaml
     emacs-lisp
     git
     multiple-cursors
     )
```

**Comment by m-fleury** [comment]
Can you put git before isabelle?
What emacs version are you using

**Comment by Torrencem** [comment]
```
emacs --version
GNU Emacs 26.3
```

**Comment by Torrencem** [comment]
also, changing the order of the layers does not fix the problem

**Comment by m-fleury** [comment]
session-async is not compatible with emacs-26... And emacs-27 is a lot faster to parse JSON (i.e., every message sent by Isabelle to emacs).

Unless I come up with something, the last point without session-async is 85bdcc21fa79ea5b4d557cd5314ae69e3590d4e4.

Supporting session-async and async should be possible in theory. But hmmm yeah.

**Comment by Torrencem** [comment]
Gotcha, I'll try to update emacs then (this will probably be a pain but I'll figure it out). Thanks so much for your fast help!

**Comment by m-fleury** [comment]
I have a clone of the emacs repo and an alias `emacs_dvl` (https://github.com/emacs-mirror/emacs) just for Isabelle  ;-)
