### ISSUE TITLE
Sledgehammer-like menu for try0?

### ISSUE THREAD

**Issue by Mesabloo** [m-fleury/isabelle-emacs#80]
This mode provides a menu for `sledgehammer` which allows not to type the whole proof (or copy/paste it) but it seems that this is not present for `try0`, despite the fact that proofs found are still numbered.
Would it be too hard to do?

**Comment by m-fleury** [comment]
```
(define-key isar-mode-map (kbd "C-c t") 'lsp-isar-insert-try-and-call)
```
Remark that we currently support only 7 solutions...

**Comment by Mesabloo** [comment]
Works like a charm!

**Comment by m-fleury** [comment]
I am closing this, feel free to open bugs if there is anything wrong (or if you need more than 7 solutions).
