### ISSUE TITLE
Sledgehammer doesn't transcribe subscripts involving special characters correctly

### ISSUE THREAD

**Issue by James-Hanson** [m-fleury/isabelle-emacs#87]
In the following example
```isabelle
locale test =
  fixes
    f :: "'a \<Rightarrow> 'a"
  assumes
    \<Phi>\<^sub>\<Phi>: "f \<circ> f = id"
begin

lemma "f \<circ> f \<circ> f \<circ> f = id"
```
sledgehammer will suggest trying ` by (simp add: \<Phi>\<^bsub>\<Phi>\<^esub>)`, which then produces the error `Outer syntax error: keyword ")" expected, but control cartouche cartouche was found`. Isabelle/jEdit produces code that looks like `by (simp add: \<Phi>\<^sub>\<Phi>)`, so I think this is actually an issue with isabelle-emacs.

**Comment by m-fleury** [comment]
I will have a look, but I suspect that it is sub/sup guessing at https://github.com/m-fleury/isabelle-emacs/blob/bd8fd356fbd373ff9e78cea09a58ba6de1d6ccfc/src/Tools/emacs-lsp/lsp-isar/lsp-isar-output.el#L387 and in the next block
