### ISSUE TITLE
Isabelle2024

### ISSUE THREAD

**Issue by halbGefressen** [m-fleury/isabelle-emacs#88]
- [ ] Isabelle2024-RC1-vsce

**Comment by m-fleury** [comment]
Thanks for the reminder, I am hijacking that issue to add my list:

- [X] Isabelle2024-RC1-vsce
- [X] Isabelle2024-RC3-vsce
- ...
- [x] Isabelle2024-vsce


Do not forget to run `./bin/isabelle components -I`
